let a = "NAME : Rajat Mishra";
let b = "SCHOOL : St. Xaviers Ahmedabad";
let c = "GRADE : 8";
let d = "SECTION : A";
let e = "ROLL NO : 45";
let f = "ENGLISH : 70/100";
let g = "MATHS : 90/100";
let h = "SCIENCE : 80/100";
let i = "TOTAL : 240/300";
let j = "RESULT : PASS";
console.log(a);
console.log(b);
console.log(c);
console.log(d);
console.log(e);
console.log(f);
console.log(g);
console.log(h);
console.log(i);
console.log(j);